name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: build tsc
        run: yarn run tsc
      - name: git setting
        run: |
          git config --local user.email "me@ebiyuu.com"
          git config --local user.name "bot"
      - name: Commit files
        run: |
          git add --force -- main.js
          git push origin gh-pages -f
